baseURL = "https://MayingS.github.io/"
languageCode = "en-us"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
publishDir = "public"

[params]
    name = "Maying Shen"
    description = "Master of Science in Computer Vision, Carnegie Mellon University"
    email = "mayings@andrew.cmu.edu"
    phone = "(412) 419-7491"
    year = 2019
    background = "images/main_background.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showEducation = true
    showExperience = true
    showProjects = true
    showPublication = true
    showRecentWorks = true
    showDownload = true
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1


[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/maying-shen-cv/"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/MayingS"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:mayings@andrew.cmu.edu"
    icon = "fa-envelope"
    footer = true
    sharethis = false
    network = "email"
